[package]
name = "js_runner"
version = "0.1.0"
edition = "2024"

[dependencies]
deno_core = "0.351.0"
once_cell = "1.21.3"
tokio = { version = "1.36", features = ["macros", "rt-multi-thread"] }
contexts = { path = "../contexts" }
domain = { path = "../domain" }